"""empty message

Revision ID: f88821d00dfa
Revises: f0e8cebd95d7
Create Date: 2022-04-25 18:24:40.812641

"""

# revision identifiers, used by Alembic.
revision = 'f88821d00dfa'
down_revision = 'f0e8cebd95d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'create_time')
    # ### end Alembic commands ###
